# Generated by Django 4.2.4 on 2023-10-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='school',
            field=models.CharField(default='exit', max_length=200),
            preserve_default=False,
        ),
    ]
