# Generated by Django 4.2.4 on 2023-10-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_person_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='price',
            field=models.CharField(max_length=200),
        ),
    ]
