# Generated by Django 4.2.4 on 2023-10-06 21:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_formsubmission_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
